### ISSUE TITLE
Confirm all launch-dependent issues and pulls tagged and have process to tag new ones in the future.

### ISSUE THREAD

**Issue by chris-remus** [ethereum/ens#113]

**Comment by chris-remus** [comment]
@Arachnid and @alexvandesande Could you please both -

- review outstanding issues and pull requests
- confirm all launch dependent issues and pull requests are tagged with the "launch dependency" tag

Also, moving forward, please use this tag for any launch dependent Issues and Pulls that emerge. 

I'm using that tag to figure out which Issues and Pulls to add to the Project. The assumptions is anything w/o the "launch dependency" tag can be addressed after launch.

Thanks!

**Comment by Arachnid** [comment]
Done!

**Comment by chris-remus** [comment]
@Arachnid Thanks! Do they include, [from you post - ](https://medium.com/@weka/7d4ab3c4a6ca)

"All of the code issues identified by the auditors will be addressed before deploying the updated contract, with the exception of two of Piper’s suggested refactors, which we believe are substantial enough that they would result in a significant rewrite of the contract, introducing additional risk."

**Comment by Arachnid** [comment]
Yup, I've tagged all of the issues resulting from those appropriately.
