### ISSUE TITLE
Populate Medium Publication with Initial Content

### ISSUE THREAD

**Issue by chris-remus** [ethereum/ens#114]

**Comment by chris-remus** [comment]
- [ ] create list
- [ ] populate publication w/content from list

**Comment by chris-remus** [comment]
list - 

- [ ] audit results - nick
- [ ] post-mortem - nick
- [ ] post-mortem - maurelian
- [ ] explaining ens - maurelian

**Comment by chris-remus** [comment]
@Arachnid What's the best way to contact Maurelian? I'd like to ask him to add a couple articles to the ENS Medium publication.

**Comment by Arachnid** [comment]
Gitter is probably the best option.

**Comment by Arachnid** [comment]
(Or @mention him on here)

**Comment by chris-remus** [comment]
Thx, contacted him through Gitter.

**Comment by chris-remus** [comment]
@Arachnid Can you cut and paste your post-mortem into a Medium article? https://docs.google.com/document/d/1Xr6JELHHWb5ONl_WvJDmIwbfShTgWpMqiNRag2IdmLI/edit#

**Comment by chris-remus** [comment]
Maurelian added his articles...

**Comment by Arachnid** [comment]
Is this done?
