### ISSUE TITLE
Deployment process, Solidity compiler version, flags...

### ISSUE THREAD

**Issue by ethers** [ethereum/ens#120]
I see that ENS.lll.bin will be deployed.

What is the process for the other contracts (hashregistrar, etc), what compiler version will be used and flags?  It would also be helpful to document the commit hash of this repro that will be used (if a tag is not created in advance).

Can the pragma be tightened up and fixed to a specific version?
`pragma solidity ^0.4.0;`
It will help with the documentation and prevent compiling with an unintended version.

**Comment by yuanfeiz** [comment]
Do you mean the process for the live net? Or development?

**Comment by ethers** [comment]
mainnet deployment

**Comment by Arachnid** [comment]
We will tag the version deployed in Github, as we have for prior versions.

I'm not sure I understand the point of specifying a single version in the pragma; it exists to specify compatible compiler versions, which will generally be "all versions after x", where x introduced a relevant bugfix or feature.

**Comment by ethers** [comment]
In development, the looser pragma can be helpful.  But in deployment, one/others will deploy with a specific version and locking it will restrict the compiler to use, especially because there's massive differences to Solidity compiler versions (0.4.0 to 0.4.10).  (Ideally, there would be a most recent "stable" version of the compiler, and the pragma would be set to it.)  It may be interesting in itself which version ENS will choose, since there are risks with using the most recent version.
