### ISSUE TITLE
Deed setBalance throwOnFailure

### ISSUE THREAD

**Issue by ethers** [ethereum/ens#121]
Should
https://github.com/ethereum/ens/blob/5c2167b9fc6290c180e3989a30b4f9f4e3213d5a/contracts/HashRegistrarSimplified.sol#L67

be updated to

```
if (value < newValue) {
  if (throwOnFailure) throw; else return;
}
```

?

Otherwise 
https://github.com/ethereum/ens/blob/5c2167b9fc6290c180e3989a30b4f9f4e3213d5a/contracts/HashRegistrarSimplified.sol#L463
can throw (if somehow the original h.value can be smaller than 0.005 ether) meaning that the name never gets invalidated.

**Comment by Arachnid** [comment]
I don't think so; that check is intended to prevent attempting to increase the value, so we don't ever want to bypass it. The value cannot be less than 0.005 ether, since we reject bids with values smaller than the minimum bid when they're submitted.
