### ISSUE TITLE
closeDeed if burn fails

### ISSUE THREAD

**Issue by ethers** [ethereum/ens#123]
It seems desirable that closeDeed should continue on even if the burn fails.

`bool unused = burn.send(((1000 - refundRatio) * this.balance)/1000));`
instead of:
https://github.com/ethereum/ens/blob/5c2167b9fc6290c180e3989a30b4f9f4e3213d5a/contracts/HashRegistrarSimplified.sol#L79

**Comment by Arachnid** [comment]
The idea here is that if the owner of the deed has a broken fallback function, they have an opportunity to fix it and call destroyDeed again themselves, rather than losing the funds permanently.
