### ISSUE TITLE
Shouldn't the owner be set at the start of unsealing process?

### ISSUE THREAD

**Issue by dilipkrbe** [ethereum/ens#130]
I'm sure I'm just missing something dumb since I am new to ETH. So my apologies in advance!

HashRegistrarSimplified.sol#367
After line 370 in the unsealBid(), shouldn't the owner be set to the message sender bid.setOwner(msgsender)? 
Also, in line 365, I guess it is a typo in the comment. I guess you meant salt instead of sale.

I am just trying to understand the code and think that this may be a bug.

**Comment by Arachnid** [comment]
It's no longer necessary to call `setOwner`, because the owner is set at creation time, on line 343.

Good spotting on the typo, thanks!
