### ISSUE TITLE
Enumerate use-cases and edge cases for auction registrar, and verify each is covered by a unit test.

### ISSUE THREAD

**Issue by chris-remus** [ethereum/ens#132]
Taken from [Nick's post-mortem.](https://docs.google.com/document/d/1Xr6JELHHWb5ONl_WvJDmIwbfShTgWpMqiNRag2IdmLI/edit#)

**Comment by chris-remus** [comment]
@Arachnid Is there an in-progress list of use-cases and/or edge cases?

**Comment by chris-remus** [comment]
@Arachnid ^ ?

**Comment by Arachnid** [comment]
Only the list I made up and sent you when you first joined. I think we've covered this point satisfactorially.
