### ISSUE TITLE
Get keyholder signatures prior to launch

### ISSUE THREAD

**Issue by chris-remus** [ethereum/ens#135]
Keyholder signatures is the last step, to update the ENS to point to the new registrar.

**Comment by chris-remus** [comment]
- [ ] Aron Fischer
- [ ] Dan Finlay
- [ ] Nick Johnson
- [ ] Juan Benet
- [ ] Piper Merriam
- [ ] Taylor Monahan
- [ ] Vlad Zamfir

**Comment by chris-remus** [comment]
@Arachnid This can be closed, correct?

**Comment by Arachnid** [comment]
Yup.
