### ISSUE TITLE
Review Issues and Pull Requests to confirm all launch dependencies are tagged.

### ISSUE THREAD

**Issue by chris-remus** [ethereum/ens#143]

**Comment by chris-remus** [comment]
w/"launch dependency" tag

**Comment by Arachnid** [comment]
Didn't we already do this?

**Comment by chris-remus** [comment]
@Arachnid Yes, wanted to be sure nothing else came up since then, since I'm using the "launch dependency" tag to ID which Issues and Pull Requests to bring into this project.
