### ISSUE TITLE
cancelBid and 2 weeks

### ISSUE THREAD

**Issue by ethers** [ethereum/ens#156]
It's not clear why 2 weeks was added:
https://github.com/ethereum/ens/commit/b4bf72a047d6d500f1c5950eb6db7ec30cb847d9#diff-c86d4bdb6d53f694977bb928d901f534R411

**Comment by Arachnid** [comment]
This was done in order to give anyone who accidentally fails to reveal when they're the sole bidder an opportunity to try again before anyone can throw away their funds.

**Comment by ethers** [comment]
#157 merged
