### ISSUE TITLE
Errors when bidding

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/ens#160]
I'm getting JavaScript errors when bidding on https://registrar.ens.domains/#exxtrafamous

"Exception from Tracker afterFlush function:"
"ReferenceError: BigNumber is not defined"
"Dummy hashes not working"

![screen shot 2017-05-04 at 14 23 06](https://cloud.githubusercontent.com/assets/731743/25705494/678459bc-30d5-11e7-99db-46e497d97307.png)

**Comment by Arachnid** [comment]
Thanks for the bug report! Can you open this again on https://github.com/ethereum/ens-registrar-dapp/issues/new, please?
