### ISSUE TITLE
Error Occurs After Clicking BID Button

### ISSUE THREAD

**Issue by kundouzhishou** [ethereum/ens#162]
i was wonderring to bid a domain http://registrar.ens.domains/#bitfury which was opened yet, but after i click the "BID" button, nothing happened. 

here is the log

![ens-bug](https://cloud.githubusercontent.com/assets/183052/25736005/e1977654-31a1-11e7-9a58-5950b4777bd5.jpg)

**Comment by yuanfeiz** [comment]
Thanks for the bug report! Can you open this again on https://github.com/ethereum/ens-registrar-dapp/issues/new, please:)
