### ISSUE TITLE
Unclear and incorrect writing on registrat.ens.domains

### ISSUE THREAD

**Issue by greggdourgarian** [ethereum/ens#166]
hi...the writing currently on the ens website is hard to read and contains a lot of mistakes.   I've quickly rewritten it here to correct what i see as the biggest issues.  If there is a github repo for it i'd be happy to put in a PR for it:

Ethereum Names
Names in Ethereum are used to send ether, to access apps and for other future uses. Names are not "bought" from anyone.  Ownership is guaranteed by willingness to lock ether for at least a year on the domain. While the ether is locked, the owner retains the rights to the domain, including the right to add extradata, create subdomains, lease, loan, sell it or do anything with another smart contract. The full process takes five days, and the amount of ether to be locked will be decided by auction. If nobody tries to claim your name in the first week, then you'll be refunded all the funds other than the minimum amount of 0.01 ether, required.

Permanent Registrar 
After at minimum a year, the owner can release the name back to the market and thereby recover their funds. When the permanent registrar is deployed, owners will have the right to move their names to the new registrar or get their ether back. The permanent registrar will probably make sitting on an inactive domain unprofitable by further locking of ether. The current registrar is temporary: it is expected that in 1 to 2 years a new update process will replace it with extra functions to discourage squatting. Names registered now are very likely to be grandfathered in the updated registrar, but you are expected to execute a transaction to move names. The current contract, will not accept registrations in 4 years, and any ether remaining on it will become irretrievable in 8 years. Keep yourself informed and be ready to transfer the name in the coming years.

Max bidding
You bid for a name by submitting the maximum amount of ether you are willing to lock for it. If you are outbid, your ether will be refunded.  If your bid wins, you will be refunded any amount your id exceed a second place bidder.  Note: therefore you only need to bid once. Your maximum bid is kept secret until you reveal it.

**Comment by Arachnid** [comment]
Thanks for the edits! The repository is at http://github.com/ethereum/ens-registrar-dapp.
