### ISSUE TITLE
Does the source include LLL?

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/ens#168]
Looking into this repo I see LLL files (e.g. [ENS.lll](https://github.com/ethereum/ens/blob/master/contracts/ENS.lll)). However the contract source code [as shown on etherscan.io](https://etherscan.io/address/0x6090a6e47849629b7245dfa1ca21d94cd15878ef#code) only seems to have solidity. Does the deployed contract use LLL?

**Comment by Arachnid** [comment]
The registry - ENS's central component - has implementations in both Solidity and LLL. The LLL version is the one deployed on mainnet [here](https://etherscan.io/address/0x314159265dd8dbb310642f98f50c066173c1259b).

**Comment by JustinDrake** [comment]
I'm confused by your link https://etherscan.io/address/0x314159265dd8dbb310642f98f50c066173c1259b

That address only has 13 transactions which date from 47 days ago. Is that the production ENS registry?

**Comment by yuanfeiz** [comment]
It's because there's no any revealed bid yet, so no domain has been registered. Those transactions are probably belong to the first launch which has been superseded by this launch.

**Comment by Arachnid** [comment]
That's correct. Also, calls from the multisig or the registrar won't show up there because they're "internal transactions".

**Comment by yuanfeiz** [comment]
"internal transaction" is new to me, thanks for the footnotes.
