### ISSUE TITLE
Has the burn functionality been tested?

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/ens#169]
As I understand the `0xdead` address is used for burning funds. When looking into [this address](https://etherscan.io/address/0xdead) I see 0 transactions. Has the burn functionality been tested on the main net?

**Comment by Arachnid** [comment]
No bids have been revealed yet, so there's no burns yet. You can see our unit tests in the repository.

**Comment by JustinDrake** [comment]
So are all the unit tests performed off-chain? Would it not make sense to have an onchain (mainnet) mock contract?

**Comment by Arachnid** [comment]
Yes; they're run against testrpc, and we've tested it on Ropsten. There's really no reason to run tests on mainnet with real ether.
