### ISSUE TITLE
Uncaught Error: Duplicate _id

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/ens#170]
My console has lots of uncaught errors:

<img width="521" alt="screen shot 2017-05-06 at 12 07 09" src="https://cloud.githubusercontent.com/assets/731743/25771857/b332e182-3254-11e7-8b76-142cc3cf3816.png">

**Comment by Arachnid** [comment]
Can you refile this on https://github.com/ethereum/ens-registrar-dapp/issues/new, please?
