### ISSUE TITLE
'watched' domain names should be sorted by availability date

### ISSUE THREAD

**Issue by tjayrush** [ethereum/ens#175]
On the UI for https://registrar.ens.domains/, the 'watch' feature is excellent, and very useful, but it should be sorted by the available auction date, or if the auction has already closed, then the reveal end date. Furthermore, you should display these dates in the watch list.

Sorting alphabetically is the obvious way to sort, but it has no utility. People are watching these names because they want to make sure not to miss the auction or the reveal period. "When" is the important factor here, so you should sort that list reverse chronological.

**Comment by yuanfeiz** [comment]
Thanks for the feature request! 
Can you please open this again on https://github.com/ethereum/ens-registrar-dapp/issues/new. 
Appreciated!

**Comment by tjayrush** [comment]
Done.
