### ISSUE TITLE
extra auctions passed to startAuctions

### ISSUE THREAD

**Issue by jpritikin** [ethereum/ens#179]
Using registrar.ens.domains and Mist 0.8.10-1708, I found that extra auctions can be passed to startAuctions. For example, I tried [startAuctionsAndBid](https://etherscan.io/tx/0x6bdce9cc6c1a70f29273ae909e1c95df764a786ac04b5e9242f4d2f1f97104bb) but this opened auctions on other names (portalzoo.eth, oc-sysnet.eth) that I don't even care about. I had to open the auction I care about in a [separate transaction](https://etherscan.io/tx/0xdaf41e13f5a5a6b5d06125862250c1a56c6c20206969bf292a642209be5e5083). This seemed to work, but it also opened spurious auctions for two seemly random hashes. Am I missing something?

**Comment by Arachnid** [comment]
This is intended behaviour; the registrar opens the auction you want (if it's not already open), plus additional random auctions to disguise the auction you're bidding on.

**Comment by jpritikin** [comment]
OK, that makes sense, but the initial startActionsAndBid did not open the auction I wanted. It opened other random auctions. Surely this is a bug?

**Comment by Arachnid** [comment]
If it did that, it was because the name you were bidding on had already been opened by someone else. If you look up the name at https://etherscan.io/enslookup does it show an auction start event from someone else?

**Comment by jpritikin** [comment]
On Thu, May 11, 2017 at 08:17:47AM -0700, Nick Johnson wrote:
>    If it did that, it was because the name you were bidding on had already
>    been opened by someone else. If you look up the name at
>    [1]https://etherscan.io/enslookup does it show an auction start event
>    from someone else?

No, I had to start the auction myself. I issued the startAuction 
transaction when I realized that the auction wasn't already open. That's 
why I suspected a bug.

**Comment by Arachnid** [comment]
Can you please link to the transactions in question?

**Comment by jpritikin** [comment]
On Thu, May 11, 2017 at 08:22:30AM -0700, Nick Johnson wrote:
>    Can you please link to the transactions in question?

I did in comments above. Do you need me to reveal the name that I bid 
on?

**Comment by Arachnid** [comment]
No, but I need to know which of those hashes is the one you intended to bid on, please.

**Comment by jpritikin** [comment]
pritikin.eth

**Comment by Arachnid** [comment]
Hm, I'm not sure then; are you positive you bid on that and not on a typo of it?

Can you reopen this bug on https://github.com/ethereum/ens-registrar-dapp with those details?
