### ISSUE TITLE
[ToDo] Select signatories for the ENS "rootnode owner" account

### ISSUE THREAD

**Issue by maurelian** [ethereum/ens#18]
If it will be owned by a multisig contract, also select/create the design of that contract.

**Comment by nmushegian** [comment]
how about using https://github.com/nexusdev/ds-multisig,

e.g.   https://makerdao.github.io/actions/

**Comment by Arachnid** [comment]
Done!

**Comment by nmushegian** [comment]
Can you re-open this until we can give a version we're a little more confident in... I think this is actually not the one used live by maker and was a rewrite with no other reviews. @dbrock @apmilen

**Comment by Arachnid** [comment]
We're actually using the Consensys multisig wallet.
