### ISSUE TITLE
accidentally started an auction for cryptogr.eth.eth

### ISSUE THREAD

**Issue by afool41** [ethereum/ens#180]
I accidentally typed in this URL   https://registrar.ens.domains/#cryptogr.eth  and then started an auction..  
Later, when I checked the actual transaction on etherscan.io , I found that an auction for legroom.eth was started  :  https://etherscan.io/tx/0x2e25d2304b8caa9b9ef2b2e9fd137da23d4fd158f206dba6037104d835e541cf  

There seemed to be a bug that caused the transition from cryptogr.eth.eth to legroom.eth .

**Comment by yuanfeiz** [comment]
When user starts a bid, it actually begins with a list of random domain auction initiatives to hide your target domain auction. So legroom.eth might be in that random list.

**Comment by afool41** [comment]
So it is not a bug?

**Comment by Arachnid** [comment]
No, it's expected behaviour.
