### ISSUE TITLE
Transaction fee so high

### ISSUE THREAD

**Issue by DSofter** [ethereum/ens#181]
Hey I was trying to bid a name on my browser using Metamask.

![image](https://cloud.githubusercontent.com/assets/1687829/26018461/e87191f8-3723-11e7-8aac-0deedf468165.png)

Just wondering why is the fee so high?

Not sure if this is the right channel. Thanks in advance!

**Comment by yuanfeiz** [comment]
Because to create a bid requires lots of operations, including to create an internal Deed contract. So it's definite higher than normal transaction.

**Comment by Arachnid** [comment]
You can set the gas price lower - as low as 2 gwei and your transaction should still be mined.
