### ISSUE TITLE
Unreadable error when trying to reveal bid with metamask from wrong account

### ISSUE THREAD

**Issue by yaronvel** [ethereum/ens#182]
By mistake I tried to reveal my bid from the wrong metamask account.
I got a lot of red messages that disappeared after two seconds.

Only after trying to do the operation manually I understood I was using the wrong account in metamask.

**Comment by russdirks** [comment]
I got a similar error message when trying to interact with the ENS dApp, but in my case I had forgotten to log into MetaMask.

**Comment by Arachnid** [comment]
This repository is for issues with the ENS solidity code and associated utilities. For the registrar DApp, please open an issue here: https://github.com/ethereum/ens-registrar-dapp/issues/new
