### ISSUE TITLE
"Out of gas" error on finalize transaction

### ISSUE THREAD

**Issue by wejustfadeaway** [ethereum/ens#183]
I am having trouble to finalizing my first won auction. I am using MyEtherWallet, which I successfully used to bid and reveal. However, when I try to finalize, I get an out of gas error. It doesn't refund me the appropriate amount over the second place bid, and doesn't list me as the owner on Etherscan, etc.

Any idea if I'm doing something wrong?

Here is one instance of a failed transaction (I tried 3X). https://etherscan.io/tx/0x9e0cb70f1befb0c80eab81f180dc4b7ec0b43414d540d87ebcba2fe97410f1ef

It is for coinality.eth (For the record, I am not Dan from Coinality, but bid on this name with his blessing).

**Comment by yuanfeiz** [comment]
I think the gas limit is too low, how about increasing it to 300000?

**Comment by Arachnid** [comment]
This was a brief bug with MEW; it should work now.
