### ISSUE TITLE
Download Bids button on the DApp returned an empty json file

### ISSUE THREAD

**Issue by DutchBoyd** [ethereum/ens#184]
Using Chrome + Metamask extension. I made a bid for "content.eth" for ~ 2.2 ETH. The transaction went through fine. 

TX ID : 0x5eba1fcd644e749d21b9311c0d0f62318f21c00e81012a98cf788b0acf817cc1

Popup window prompted to download bids. Clicked the button and downloaded an empty json file. I open and check these right away, and the file just contained a single line:

[]

I clicked the download button again. Downloaded another empty json file. I start panicking. Shut down Chrome. Restart. Watchlist is still there. Export bids link on the bottom right is nowhere to be found. I go to the console. 

Try typing MyBids.findOne{("content")}. Undefined. I look in local storage. It's full of stuff. I filter for "content" but  only see a hash: and _id: value. Nothing that looks like a secret or hexSecret that I might be able to import in the DApp or over at MEW. 

I feel deflated and afraid to make another bid through the DApp. I'm keeping my computer powered on, hoping I might be able to figure out a way to pull that secret out of memory. Also thinking maybe there'd be a way to pull it out of my home router. Or perhaps a way to regenerate it using my Metamask private key. 

I would suggest perhaps allowing (or even requiring) users of the DApp to submit their own generated secret as MEW does. Any help or advice you guys can give me would be greatly appreciated. 

[ens-bids-backup_2017-05-14T01-52-53.135z.json.txt](https://github.com/ethereum/ens/files/999113/ens-bids-backup_2017-05-14T01-52-53.135z.json.txt)

**Comment by Arachnid** [comment]
Can you please reopen this on https://github.com/ethereum/ens-registrar-dapp/issues/new?
