### ISSUE TITLE
Wrong result from "ethRegistrar.entries" call ?

### ISSUE THREAD

**Issue by xiaojay** [ethereum/ens#187]
I just follow the [http://docs.ens.domains/en/latest/userguide.html#registering-a-name-with-the-auction-registrar](docs), try to  check if the name "skycasino" is available.  The name "skycasino"should be available, which is confirmed on http://registrar.ens.domains/ and https://etherscan.io/enslookup。Howerver, the geth js console return a different result, like below:

<img width="864" alt="2017-05-16 4 49 51" src="https://cloud.githubusercontent.com/assets/150021/26097795/43d65f7e-3a58-11e7-8683-3a4ba2ede333.png">

what is wrong? I am pretty sure my geth is fully synced.

**Comment by Arachnid** [comment]
This is correct; state 0 means the name is available for auction.
