### ISSUE TITLE
Revealing via MEW

### ISSUE THREAD

**Issue by belgacoin** [ethereum/ens#188]
Hi,

Can anyone verify my revealing please? I don't think it worked as it should.
https://etherscan.io/tx/0x68f5b15c2716c314fbef801472b447902cc6a682423ab12a1ad9849a280c175e
As you see, the domain isn't mentioned.
In MEW, all fields are in green.
thanks

**Comment by Arachnid** [comment]
That's not a reveal; it's a bid, which was placed fine.
