### ISSUE TITLE
ties for high bid should lock the full amt of high bid

### ISSUE THREAD

**Issue by rboyd** [ethereum/ens#199]
I might be wrong but eyeballing the branching logic on comparing bids in unsealBid, doesn't a tie for the high bid currently fall through the final else clause? I think in this case the winner ought to lock the full amount of his bid ([What happens in a Vickrey auction when the top two bids are the same?](https://www.quora.com/What-happens-in-a-Vickrey-auction-when-the-top-two-bids-are-the-same))

https://github.com/ethereum/ens/blame/master/contracts/HashRegistrarSimplified.sol#L417-L425

I think L417 clause should include the tie:
`else if (value > h.value || value == h.highestBid)`

Am I reading it wrong? @alexvandesande

**Comment by Arachnid** [comment]
No; the first bid revealed will trigger the statement on line 403, the second will trigger the statement on line 417. Subsequent ties will trigger the final else clause.
