### ISSUE TITLE
Deploy ENS and Initial Registrar on Morden

### ISSUE THREAD

**Issue by maurelian** [ethereum/ens#20]
See Deployment and Upgrade process of https://github.com/ethereum/EIPs/issues/162

**Comment by scottdmc** [comment]
Has it been deployed to Morden network?

**Comment by Arachnid** [comment]
Not yet; we're waiting on a usable DApp for registrations before we launch.

**Comment by zigguratt** [comment]
I believe we're live on Ropsten now.

**Comment by Arachnid** [comment]
We are, at `0x112234455c3a32fd11230c42e7bccd4a84e02010`. Once documentation is up, I'll announce more publicly.
