### ISSUE TITLE
still having issues with refunds!

### ISSUE THREAD

**Issue by yoavile** [ethereum/ens#200]
what happened here why didnt i get refunded???

https://etherscan.io/tx/0x881f1e5c6f3cafeb69997f216c73cf823680f5703faa443ad17348667cca457c#internal

also seems i had a bid, i revealed it, but its not registering (im guessing it didnt go through), reveal fase is now over, did i lose the name and the ether i bid??? or how do i get it back?? (bidded 2.51 eth and revealed (not registering) for winstonchurchill.eth)

thanks

**Comment by Arachnid** [comment]
Do you work for Consensys?

**Comment by yoavile** [comment]
no

**Comment by yoavile** [comment]
i dont even know what that is

**Comment by yoavile** [comment]
if i bidded and cannot find the information to reveal the bid, did i necessarily loose those funds??

**Comment by Arachnid** [comment]
You didn't get refunded in that transaction because you were still the leading bidder at that point. You got refunded [when you were outbid](https://etherscan.io/tx/0x4a9b7673a4fc89f729222e6c98a5891cbdda9e09e78dc8d1061116b447ebfc6a).

**Comment by yoavile** [comment]
thanks so much you are very helpful! im new to this....

i have a bid which i cant find the info to reveal - 0xd585131038a1b6aa8b811ee13053e7d550b5609570334cf595852683fc018771

am i screwed???

**Comment by Arachnid** [comment]
Yes, if you didn't retain the information needed to reveal, there is no way to recover your bid.

**Comment by yoavile** [comment]
shit....
and can i reveal after the auction ended if im a losing bid..?

**Comment by yoavile** [comment]
or for a winning bid? can i reveal after its ended?

**Comment by Arachnid** [comment]
No, you cannot reveal after the auction ends.

**Comment by yoavile** [comment]
shit.

thanks man appreciate your help.

**Comment by hitchcott** [comment]
@Arachnid  Seems like there is conflicting information about revealing after the auction is ended if there are no other bidders. The wording in the ENS dapp says that if you don't reveal, you will lose your bid forever, but when the auction is over (after the reveal period when nobody bids), the dapp says (incorrectly) that "you have been refunded". Can this be clarified? 

@yoavile According to MEW you can still reveal if you start the auction again (worth a try):

https://myetherwallet.groovehq.com/knowledge_base/topics/i-forgot-to-reveal-my-name-on-an-auction-with-no-other-bidders-what-do-i-do
