### ISSUE TITLE
Bid lost bug

### ISSUE THREAD

**Issue by zyy96168** [ethereum/ens#202]
If you have previously bid, then import your bids backup to see and reveal them. "Make sure I have to follow the prompts to back up the BID and press the" The same operation is not all the applications are lost, only lost four. I have this problem domain name "netcoin.eth", "hongkong.eth" "unionpay.eth" "porte -monnaie "what method should I use to find the four domain name of the ether.

**Comment by Arachnid** [comment]
The repository for the DApp is ethereum/ens-registrar-dapp.

**Comment by zyy96168** [comment]
Can not find "dns-registrar-dapp". I backed up the BID, it saved as * .json file. But can not restore the four domain name. I just want to return to my coin. Please help.
