### ISSUE TITLE
ENS name file is missing help

### ISSUE THREAD

**Issue by zyy96168** [ethereum/ens#205]
I backed up the BID, it saved as * .json file. But can not restore the four domain name. I just want to return to my ETHER. Please help。I have lost domain names "netcoin.eth", "hongkong.eth" "unionpay.eth" "porte -monnaie "
![qq 20170529051916](https://cloud.githubusercontent.com/assets/23380034/26578378/eeaf0630-452f-11e7-8062-6018ae51940c.png)
not find "ethereum/ens-registrar-dapp.".

**Comment by Arachnid** [comment]
Please open bugs on the dapp at ethereum/ens-registrar-dapp, and for support requests, ask on the Reddit or Ethereum Stack Exchange.
