### ISSUE TITLE
ens registry

### ISSUE THREAD

**Issue by gzcharles** [ethereum/ens#208]
i registry in myetherwallet cx, but it always failed when i set resolver. TX as below

To:Contract 0x314159265dd8dbb310642f98f50c066173c1259b (ENS-EthNameService)  
 Warning! Error encountered during contract execution [Bad jump destination] 

so what should i do next?

**Comment by jkcailteux** [comment]
I have been seeing this every time on multiple domains, different clients, in different states.

**Comment by veox** [comment]
@gzcharles Is the auction for that name finalised?

Are you providing enough gas with the tx?

Can you link the tx?

**Comment by AMOz1** [comment]
I have the same issue.. here is my TxHash
https://etherscan.io/tx/0x2c5981cf74a1db592bf36e10ba0cc35c6b3158ab57f7ee66c43b6c94b492c071

**Comment by Arachnid** [comment]
Setting the resolver will fail if you don't own the node in question. Make sure you own it first.

**Comment by AMOz1** [comment]
sorry but I don't understand "don't own the node in question"
I was following the instructions on this link
https://myetherwallet.groovehq.com/knowledge_base/topics/how-do-i-set-the-resolver-for-a-name

I was able to set one .eth name couple of weeks ago... without this error

**Comment by Arachnid** [comment]
The node is the hash of the full name. Are you sure you're entering the nodehash, not the labelhash? Are you sure you finalised your domain? Are you sure you sent the TX from the account that owns that name?
