### ISSUE TITLE
No ACCEPT option for refund after REVEAL of bid for CURRENCIES.ETH

### ISSUE THREAD

**Issue by ladyze** [ethereum/ens#218]
Dear Sir/Madame, 

On June 20 and June 21, I attempted to bid a total of 0.77, 0.76, 0.75 and 0.72 to secure name CURRENCIES.ETH; unfortunately, all of these attempts were 'Rejected' or 'Failed'. I either did not receive confirmation of this bid or if I did, my MetaMask does not show an approved transaction for CURRENCIES.ETH. Auction site https://registrar.ens.domains/#currencies however, indicates that 'You are willing to pay at most: 0.74 ether; 0.01 ether will refunded when you reveal your bid.' When I click on the REVEAL button to obtain these funds back (which were somehow withdrawn from my MetaMask Ethereum Main Net network without confirmation), MetaMask notification indicates that there is 'Insufficient balance for transaction' and I am unable to ACCEPT reveal to obtain these funds back. 

**Please review this transaction for CURRENCIES.ETH and refund 0.74 + 0.01 ETH back to my account before auction ends early 06/24.** Please also inform zomarawilson@gmail.com if there is any further information you need from me in order to resolve issue. Thank you for your time as I look forward to a speedy resolution.

**Comment by Arachnid** [comment]
> When I click on the REVEAL button to obtain these funds back (which were somehow withdrawn from my MetaMask Ethereum Main Net network without confirmation), MetaMask notification indicates that there is 'Insufficient balance for transaction' and I am unable to ACCEPT reveal to obtain these funds back.

You need to place enough funds in your account to be able to send the reveal transaction, or you will not be able to send it and recover your ether.

> Please review this transaction for CURRENCIES.ETH and refund 0.74 + 0.01 ETH back to my account before auction ends early 06/24.

ENS is a distributed system. We have no access to your funds, and it's up to you to follow the rules of the contract when interacting with the system.

**Comment by ladyze** [comment]
Regarding https://github.com/ethereum/ens/issues/218:

Thank you Arachnid for your quick reply. Per your suggestion, I placed additional funds in my MetaMask account to be able to send the reveal transaction. After I did this, I received https://registrar.ens.domains/#currencies confirmation that "...since someone else was willing to pay more, your full deposit was returned, minus a bidding fee of 0.0037 ether which was burned." However, according to MetaMask's Ethereum Main Net network, I did not receive my 0.74 ether deposit as confirmed on registrar.ens.domains for CURRENCIES.ETH.

- Would someone from your end be able to review this transaction for me?
- Or should I contact MetaMask regarding refund that was not received?

Thank you for your time as I look forward to hearing from you soon.

Kind regards,

Zee Wilson
zomarawilson@gmail.com
Cell: (646) 228-4573

**Comment by ladyze** [comment]
Regarding https://github.com/ethereum/ens/issues/218:

Thank you for your quick reply. Per your suggestion, I placed additional
funds in my MetaMask account to be able to send the reveal transaction.
After I did this, I received https://registrar.ens.domains/#currencies
confirmation
that "...since someone else was willing to pay more, your full deposit was
returned, minus a bidding fee of 0.0037 ether which was burned." However,
according to MetaMask's Ethereum Main Net network, I did not receive my
0.74 ether deposit as confirmed on registrar.ens.domains for CURRENCIES.ETH.

   - Would someone from your end be able to review this transaction for me?
   - Or should I contact MetaMask regarding refund that was not received?

Thank you for your time as I look forward to hearing from you soon.

Kind regards,

Zee Wilson
zomarawilson@gmail.com
Cell: (646) 228-4573

**Comment by Arachnid** [comment]
Your ether was returned; you can see it in the 'internal transactions' tab on etherscan.

**Comment by ladyze** [comment]
Thank you for informing where I may see this ether return. I do see in
etherscan's "internal transactions" that 0.7363 Ether has been sent back to
my account 0xc5894ecb9951453... However, this $265.13 amount still has not
been deposited back into my Ethereum Main Network in MetaMask, where I
received these funds from.

   - Would you be able to manually refund 0.7363 ether back to my MetaMask
   Ethereum Main Network account?
   - Or is there another place where I may access and withdraw these funds
   (perhaps within Etherscan)?

Thank you for your time as I look forward to hearing from you soon.

Kind regards,

*Zomara Wilson*
zomarawilson@gmail.com
