### ISSUE TITLE
26 failed transactions at https://registrar.ens.domains!

### ISSUE THREAD

**Issue by rdmiller1** [ethereum/ens#219]
I experienced 26 failed transactions over the past 48 hours at https://registrar.ens.domains. This cost me somewhere in the neighborhood of $200! Most of these failed with the message "bad instruction". My experience at this site was that only about 10% of my transactions were successful. There was no rhyme or reason to when the system would fail. Eventually, I realized I could apply for ENS names through myetherwallet, which worked flawlessly.

I would like to be compensated for this approximate $200 loss. I can send the etherscan data to document this.

**Comment by Arachnid** [comment]
I'm sorry you've run into bugs. Gas costs are your own responsibility; this is spelled out quite clearly in the 'understand the process' dialog on the Dapp.

If you'd like to help us track down the bugs, please submit as much detail as you can about the failed transactions at https://github.com/ethereum/ens-registrar-dapp/issues/new.
