### ISSUE TITLE
ENS dApp didn't recognize I had canceled MetaMask transaction

### ISSUE THREAD

**Issue by russdirks** [ethereum/ens#220]
Steps to reproduce:

1. Enter a domain name
2. Click on the link "Open without bidding"
3. In the MetaMask pop-up, click the Reject button
4. Back in the ENS dApp, click Bid button
5. MetaMask will  pop up requesting a transaction confirmation.  Accept the transaction.  
6. Immediately after, MetaMask will pop up another transaction.

It seems like either MetaMask or the ENS dApp did not register the fact I canceled the first transaction

**Comment by Arachnid** [comment]
This repository is for issues with the ENS solidity code and associated utilities. For the registrar DApp, please open an issue here: https://github.com/ethereum/ens-registrar-dapp/issues/new
