### ISSUE TITLE
Transfering a name

### ISSUE THREAD

**Issue by rdmiller1** [ethereum/ens#221]
I have been unable to find any directions for using the app at ENS Registrar. If this exists, please tell me where it is.

After running into many errors with this software, I have finally finalized a bid on a name. I would now like to transfer ownership from this account to MyEtherWallet account. The software is asking me this question:

"Account to transfer the name to:"

Can I simply enter my public key for MyEtherWallet account, or is it looking for some other piece of information?

**Comment by Arachnid** [comment]
This repository is for issues with the ENS solidity code and associated utilities. For the registrar DApp, please open an issue here: https://github.com/ethereum/ens-registrar-dapp/issues/new
