### ISSUE TITLE
Weird max threads message

### ISSUE THREAD

**Issue by tjayrush** [ethereum/ens#222]
<img width="210" alt="screen shot 2017-06-28 at 10 00 31 am" src="https://user-images.githubusercontent.com/5417918/27641328-84d30560-5be9-11e7-9c17-fdda51ada23d.png">

<img width="745" alt="screen shot 2017-06-28 at 10 00 25 am" src="https://user-images.githubusercontent.com/5417918/27641204-39b47352-5be9-11e7-872c-c696e33b3bd5.png">

**Comment by Arachnid** [comment]
This appears to have been an issue with cloudflare, now fixed.

**Comment by tjayrush** [comment]
It's working
