### ISSUE TITLE
Misleading /Loading errors

### ISSUE THREAD

**Issue by rstormsf** [ethereum/ens#224]
![screen shot 2017-07-03 at 5 17 22 pm](https://user-images.githubusercontent.com/9360827/27810786-7eeba80e-6013-11e7-857f-6927958a1f20.png)
Clearly, Metamask was loaded and identified that I own the account,
However, I still see the error that my Browser doesn't support Smart Contracts.

2) It says: *Owner hasn't set up anything yet.* What else can the owner setup ?

**Comment by Arachnid** [comment]
Can you please open this issue on https://github.com/ethereum/ens-registrar-dapp/issues/new
