### ISSUE TITLE
"Browser not compatible" when using Parity on Firefox

### ISSUE THREAD

**Issue by jcramer** [ethereum/ens#226]
I am using Ubuntu 16.10 with Firefox 54.0 64-bit.  When I visit ens.domains I see the message at the bottom of the page telling me my browser isn't compatible.  I don't have this issue on my windows machine using firefox.  Any thoughts?

![parity bug](https://user-images.githubusercontent.com/988195/28269830-68cf6b1e-6ad1-11e7-85f5-21642af3afdb.png)

**Comment by Arachnid** [comment]
Please open issues relating to the registrar at ethereum/ens-registrar-dapp.
