### ISSUE TITLE
Why is there no "reveal" button?

### ISSUE THREAD

**Issue by zyy96168** [ethereum/ens#227]
![3403](https://user-images.githubusercontent.com/23380034/28486296-58f93086-6eb3-11e7-9029-80c473c2d831.png)
display"You are still the top bidder."But i can not reveal bids, how do i do? After two days I can only get 1% ether.
This is its tender information     https://etherscan.io/enslookup?q=tickets

**Comment by zyy96168** [comment]
0xB4f1c9554b7818A6711D022Ec78ec4953c6610e9
This is the public key to apply for "yaojiang.eth"

**Comment by Arachnid** [comment]
Please open issues relating to the registrar app at ethereum/ens-registrar-dapp.
