### ISSUE TITLE
Unable to open auction

### ISSUE THREAD

**Issue by DSofter** [ethereum/ens#232]
Hello guys! I opened a bid for a domain name but forgot to reveal it. Now i'm not able to open the auction:

![image](https://user-images.githubusercontent.com/1687829/29991454-fcb82300-8f3b-11e7-87ed-a2ba4adcb825.png)

Any idea what I should do?

Thanks!

**Comment by DSofter** [comment]
NVM i waited until the dictionary is loaded, and now it's fine.

**Comment by DSofter** [comment]
Actually, if people don't mind me reopening this ticket. Loading the dictionary seems to taking very long.

![image](https://user-images.githubusercontent.com/1687829/29991760-bdcb1264-8f41-11e7-9cff-cfc503c33a0c.png)

Also what does `loading dictionary` mean? What's `dictionary`?

**Comment by Arachnid** [comment]
This belongs on ethereum/ens-registrar-dapp.

**Comment by DSofter** [comment]
@Arachnid Thank you!
