### ISSUE TITLE
ENS Name Service should have verified source code on Etherscan.

### ISSUE THREAD

**Issue by MicahZoltu** [ethereum/ens#236]
https://etherscan.io/address/0x314159265dd8dbb310642f98f50c066173c1259b#code is unverified.  In order for ENS to run trustlessly, it must be verifiably audited and right now that isn't realistic for the casual observer.

**Comment by Arachnid** [comment]
The ENS registry implementation deployed on mainnet is the LLL implementation, and Etherscan does not presently support verifying LLL code.

**Comment by ligi** [comment]
seems this is solved now: https://discuss.ens.domains/t/ens-registry-verification-on-etherscan/1208/4
