### ISSUE TITLE
General Question: Reverse Lookup ENS

### ISSUE THREAD

**Issue by kibalock** [ethereum/ens#241]
Is there any kind of reverse lookup for ENS? I updated my mist client and it no longer shows any of the watched names that I own.

Here is my associated wallet address: f2f3fe8ea331e5d973807e410d06142799b8fb5e

**Comment by Arachnid** [comment]
It sounds like you're looking for a list of names you own, rather than doing reverse lookups. There's tools that can do this (eg, etherchain) but there's no single function you can call onchain to get a list.
