### ISSUE TITLE
.eth support: submit application to ICANN for newgTLD round in 2020

### ISSUE THREAD

**Issue by HLFH** [ethereum/ens#264]
Hi,

There are too many issues of cybersquatting and copyright infringments with Ethereum Name Service.
The ENS & Ethereum Foundations should apply for .eth support in the newgTLD ICANN round in 2020.
It would cost around 180K$ to submit it, and will allow to reduce cybersquatting thanks to improved UDRP requests customized for Ethereum blockchain use-case.

Thank you,
HLFH

**Comment by Arachnid** [comment]
We've already considered this; unfortunately 'eth' is the three letter ISO code for Ethiopia, so ICANN will not consider allocating it as a gTLD.

**Comment by drhus** [comment]
humm while many ccTLD of countries been subsidized or sponsored corporate and rebranded as of .Co and .Tv etc (Colombia, and Tuvalu) there might be something to be done here with Ethiopia, ... do they have control over it already? 

maybe alternatively Ethereum Foundation should consider applications for .ether, .ethereum and .crypto
