### ISSUE TITLE
Uneven consequences for paying less than the value bid

### ISSUE THREAD

**Issue by maurelian** [ethereum/ens#30]
My analysis of what happens when the value of the bid is higher than the 
amount submitted. Thanks @rfikki for inquiring about the behaviour related to underpaying for a bid.

1. When you submit a new bid, a deed contract is created. The full amount of ether you submitted (let's say 3 ETH) is [sent to that Deed](https://github.com/ethereum/ens/blob/master/HashRegistrarSimplified.sol#L270). 
2. When you then unseal your bid, revealing the value of your actual bid (let's say 3 ETH) one of two things can happen: 
    
    1. The current highest bid for `foobarbaz.eth` is 4 ETH. You do not win. The registrar thus [closes the deed](https://github.com/ethereum/ens/blob/master/HashRegistrarSimplified.sol#L319), [refunding](https://github.com/ethereum/ens/blob/master/HashRegistrarSimplified.sol#L71) 99.9% of the amount submitted.
    
    1. The current highest bid for `foobarbaz.eth` is 2 ETH. You are the highest bidder so far! In this case, the registrar will try to [update the balance](https://github.com/ethereum/ens/blob/master/HashRegistrarSimplified.sol#L313) held by the deed, and refund the difference between your balance (3 ETH) and your bid (6 ETH). But it [expects your balance to be greater](https://github.com/ethereum/ens/blob/master/HashRegistrarSimplified.sol#L62) than your bid value, when it turns out that's not true, it throws. 

From what I can see it looks like that's a lopsided outcome. 

__If you bid more than you submit and you are the highest bidder__, then your funds are locked in the deed. (Using [Deed.setBalance](https://github.com/ethereum/ens/blob/master/HashRegistrarSimplified.sol#L60))
__If you bid more than you submit and you are *NOT* the highest bidder__, then your funds will be refunded. (using [Deed.closeDeed](https://github.com/ethereum/ens/blob/master/HashRegistrarSimplified.sol#L71))

The key difference is that `Deed.setBalance` actually compares your `balance` to your bid `value`. `Deed.closeDeed` doesn't.

**Comment by pirapira** [comment]
I guess the second case should read "If you bid more than you submit and you are **not** the highest bidder".

**Comment by maurelian** [comment]
Yes, thanks for pointing that out. I edited the original accordingly.

**Comment by Arachnid** [comment]
This was resolved in the state-based rewrite of the contract.
