### ISSUE TITLE
Sub domains?

### ISSUE THREAD

**Issue by justinmchase** [ethereum/ens#31]
Suppose I were to buy `justinmchase.eth`, but then I want `example.justinmchase.eth` as well?

It seems like it would be nice to be able to have unlimited subs for any domain you may have acquired. Is this possible or planned? Or would I need to manage them all individually through auction? Or am I thinking about it all wrong?

**Comment by Arachnid** [comment]
Yes; the owner of any domain can create any subdomain they like. In fact, registrars are just owners of domains that offer to make subdomains for you if you follow the rules encoded into their contract.
