### ISSUE TITLE
Genaral questions regarding bids

### ISSUE THREAD

**Issue by Mindgameproject** [ethereum/ens#37]
What does this means?

Attention: You must reveal your bid within 24 hours of the reveal phase, failing to do so will result in irreversible loss of funds

And this?

The top bidder will own the name, but you will be refunded of any amount more than the strictly necessary to overbid the second place, therefore you only need to bid once. Your maximum bid is kept secret until you reveal it.

Why i need to reveal my bid? What is protect anonymity? What is this %? If some name already bidded like "insurance" why cant i post my bid to this?

What does those titles means

Points to: 0x18ee4d627b7c1951a209b75a20e3296e434a4ad6

Owned by: 0x8394a052eb6c32fb9defcaabc12fcbd8fea0b8a8

Deed address: 0x268e06911ba1ddc9138b355f9b42711abbc6eaec

Content: not set

**Comment by Arachnid** [comment]
> Attention: You must reveal your bid within 24 hours of the reveal phase, failing to do so will result in irreversible loss of funds

It means that you must reveal your bid during the 24 hour reveal phase, or you will lose any money you bid.

> The top bidder will own the name, but you will be refunded of any amount more than the strictly necessary to overbid the second place, therefore you only need to bid once. Your maximum bid is kept secret until you reveal it.

If you bid the most, you pay the price of the second-highest bidder. For instance, if A bids 1, B bids 2, and C bids 3, C wins, but only has to pay 2.

> Why i need to reveal my bid? What is protect anonymity?

When you bid, you only submit some ether and a hash; revealing your bid shows the actual amount and the name you were bidding on. Revealing your bid is how auctions are resolved.

> If some name already bidded like "insurance" why cant i post my bid to this?

Because that name has already been sold; you can't take it from the owner.

**Comment by Mindgameproject** [comment]
What are those percentage amounts that i can regulate during choosing a bid?

**Comment by Arachnid** [comment]
I don't understand the question.

**Comment by Mindgameproject** [comment]
What are those percentage amounts that i can regulate during choosing a bid?
![image](https://cloud.githubusercontent.com/assets/23434502/21965851/3fdf3db6-db79-11e6-889a-6a7da12972f3.png)

**Comment by Arachnid** [comment]
You can send more than your bid, to disguise the exact amount of your bid. The slider selects how much extra you're sending.

**Comment by Mindgameproject** [comment]
What does those titles means

Points to: 0x

Owned by: 0x

Deed address: 0x

Content: not set

**Comment by miketheguy** [comment]
Hi,
I don't quite understand the 'reval'-process. How do I reveal my bids on a domain? I'm using Mist!
Tx

**Comment by Arachnid** [comment]
If you're using the registrar DApp, it will do it for you - as long as you come back during the reveal period. If you registered your domain using the contract directly, you have to come back and call the `unsealBid` method yourself.

Disguising the exact amount makes it more difficult for people who have guessed what name you are bidding on to also guess how much you're bidding.

**Comment by miketheguy** [comment]
Tx a lot Arachnid,

that's very helpful! But where can I download the registrar contract DApp? Didn't find it on https://github.com/ethereum/ens/.
I currently just surfed to http://registrar.ens.domains/#ethpool via MIST. There I could register a name, but coming back during the reveal period, didn't change anything? I only can watch the name.

I also can't bid on my name, using a different wallet. Bidding seems to be still disabled! It also was disabled during the short life on mainnet.

Tx for your patience :)

**Comment by Arachnid** [comment]
Bidding is disabled until we relaunch. The source can be found at https://github.com/ethereum/ens-registrar-dapp.

**Comment by jasonsmythe8** [comment]
@Arachnid Mist is freezing when I attempt to reveal my bids on ENS Registrar.  The first name revealed and finalized with no issues at all.   I have read that the disguise bid amount needs to be at least as much as the actual bid.  I have to restart Mist constantly.  I'm on MacOS 10.12.4 with Mist v0.8.10.
[Node log.zip](https://github.com/ethereum/ens/files/999917/Node.log.zip)
