### ISSUE TITLE
invalidateName pays 50% to previous owner

### ISSUE THREAD

**Issue by kvhnuke** [ethereum/ens#46]
I believe invalidateName pays 50% to the previous owner, I didnt test but just wanted to get it out here before I forget
https://github.com/ethereum/ens/blob/master/HashRegistrarSimplified.sol#L449-L450
since the deed owner is not yet set to msg.sender, when you call setBalance(uint newValue) with 0.5 of the value the rest seems like going back to the previous owner
https://github.com/ethereum/ens/blob/master/HashRegistrarSimplified.sol#L70

I think these two needs to switch
https://github.com/ethereum/ens/blob/master/HashRegistrarSimplified.sol#L450-L451

**Comment by alexvandesande** [comment]
Thanks! This is a case of the comment being wrong and the code being correct. Owner would get 50% and invalidator 50%.
