### ISSUE TITLE
Race condition in `startAuction`

### ISSUE THREAD

**Issue by Arachnid** [ethereum/ens#54]
`startAuction` and `startAuctions` throw if the auction was already in progress. This results in a race condition, where if two people open the same auction, one selected at random will get an error.

Instead, we should silently do nothing if the auction was already running, and only throw if the name is in a different state (owned, forbidden, reveal).

**Comment by alexvandesande** [comment]
Why not return it on owned and forbidden also? It would actually make one scenario easier: when opening multiple auctions I could put some that were randomly selected from the preimage list, to further hide the true intent. I can't do it now as there would always be a chance of some names being owned and throwing the whole thing. 

Maybe just add a true false return and never throw in this case

**Comment by Arachnid** [comment]
I don't think I agree; trying to set something to 'auction' when it already is is a noop, but trying to set something to 'auction' when it's in a state that cannot transition to auction should always be an error.
