### ISSUE TITLE
Treat ENS as authoritative record of ownership?

### ISSUE THREAD

**Issue by Arachnid** [ethereum/ens#56]
If we rely on the owner field of ENS for a domain, we can transparently support an upgrade process where old domains remain under the control of the original registrar - eg, we'll never try to auction off a domain that was given out by a previous registrar. This would make certain types of upgrade much simpler.

**Comment by clowestab** [comment]
EIP 162 states "This Initial Registrar contract will be replaced with a permanent registrar contract."

The 'Simplified Hash Registrar' code states "The plan is to test the basic features and then move to a new contract in at most 2 years, when some sort of renewal mechanism will be enabled."

Wasn't the whole plan/point that registrars can be 'upgraded' - is this 'issue' essentially proposing a complete change of plan?

**Comment by Arachnid** [comment]
No, this issue is proposing an easier way to handle upgrades _during_ the initial period. Currently, if we replace one initial registrar implementation with another, the process of ensuring it doesn't accidentally 'reauction' names is more involved.

**Comment by Arachnid** [comment]
On further reflection, this is a bad idea - it means that there's no longer one authoritative source of information on a name (the registrar's map), which introduces nasty edge cases around upgrades, invalidation, and releasing names.
