### ISSUE TITLE
Inconsistency of naming .sol files

### ISSUE THREAD

**Issue by mikhail-vladimirov** [ethereum/ens#60]
Most of the .sol files are named after smart contracts defined in them, but there are several exceptions:

1. ResolverInterface.sol (defines AbstractPublicResolver smart contract)
2. interface.sol (defines AbstractENS smart contract)
3. HashRegistrarSimplified.sol (defines Deed and Registrar smart contracts)

This inconsistency makes it harder to navigate through the come and makes code reviews less efficient which in turn may lead to missed bugs.

**Comment by yuanfeiz** [comment]
Resolved 2. in #106
