### ISSUE TITLE
Name still can be used after Deed was released

### ISSUE THREAD

**Issue by mikhail-vladimirov** [ethereum/ens#64]
Not sure whether this is a bug or expected behaviour.

Function releaseDeed of Registrar smart contract reset owner of the node but does not reset resolver associated with it.  It also does not do anything with descendants of the node.  This means that node itself as well as its descendants will be resolvable even after deed was release.  More over, former owner of the node will still be the owner of all descendant nodes.

If this is a bug, it should be fixed.  If not, this behaviour should be clearly documented in EIP-162 or somewhere else.

**Comment by Arachnid** [comment]
Resetting the resolver field would be fairly easy, but as you observe, there's also descendent fields, and there's no generalised way to reset them onchain. For now, I'd settled on ignoring this, as any name you tried to claim this way would soon be overwritten by the next person to buy it.

We could provide a method similar to `invalidateName` that allows  anyone to zero out a registry record for a name they can prove is rooted at a forbidden or unowned name. Thoughts?

**Comment by mikhail-vladimirov** [comment]
Then it should probably be clearly documents, that after one releases a deed, he still may use and control corresponding name and its subnames, until somebody else will buy this name and perform clean up; and that when you buy some name, you will probably need to clean up all its descendants to prevent fishing attacks.  Otherwise an attacker may use "subdomain" of a name you bought, that is still under his control, to convince people that he acts on your behalf.

**Comment by Arachnid** [comment]
I'm working on a PR that will allow anyone to zero out a record associated with an unowned name. There's no generalised way to automatically clean them out, though, so yes, anyone buying a previously-owned name will have to take care to take control of all existing names. ENS management DApps are likely to show you your complete zone when working on it to facilitate this, though.

**Comment by Arachnid** [comment]
Fixed in PR #66.
