### ISSUE TITLE
Deed creation is not atomic

### ISSUE THREAD

**Issue by mikhail-vladimirov** [ethereum/ens#67]
It seems that Deed's value is always supposed to be less or equal to Deed's balance.  Though, Deed creation, as it is implemented in Registrar smart contract, is not atomic.  Deed is first created with some value and zero balance (https://github.com/ethereum/ens/blob/master/HashRegistrarSimplified.sol#L305) and then its balance is resupplied with exact same value (https://github.com/ethereum/ens/blob/master/HashRegistrarSimplified.sol#L309).

Deed creation could be made atomic via payable constructor:

```
function Deed() payable {
    ...
    value = msg.value;
}
```

That could be called like this:

```
Deed newBid = (new Deed).value(msg.value)();
```

Such refactoring will make default function in Deed contract probably not needed.

**Comment by Arachnid** [comment]
You're right; it used to be that it wasn't possible in Solidity to send value along with the constructor, but now that it is, this could be restructured to be neater.
