### ISSUE TITLE
Invalid opcode instead of invalid jump

### ISSUE THREAD

**Issue by xavierlepretre** [ethereum/ens#69]
I run `npm test` and the `assert` here https://github.com/ethereum/ens/blob/f24df55d4c7378e46be7b49085d6e9041be310f7/test/ens_test.js#L73 fails with, in short:

```javascript
AssertionError: Error: VM Exception while executing transaction: invalid opcode
    at Object.callback (/home/vagrant/DAPPS/ens/test/ens_test.js:73:11)
```

My versions are:

* OS: vagrant-ubuntu-trusty-64
* NodeJs: v6.10.0
* Mocha: 3.2.0
* project's `node_modules` testrpc: 2.2.4
* project's `node_modules` solc: 0.4.10
* project's `node_modules` web3: 0.16.0

The test at line 53 passes.

**Comment by Arachnid** [comment]
This is a change in recent versions of Solidity. I'll update the tests to not care what error they get back - thanks for the heads-up.

**Comment by xavierlepretre** [comment]
I forced `"solc": "0.4.9"` and the test passes. 👍
