### ISSUE TITLE
Bid that was not unsealed during auction could be reused in the next auction for the same name

### ISSUE THREAD

**Issue by mikhail-vladimirov** [ethereum/ens#74]
Registrar smart contract refunds only 0.5% of bid value to bidders who didn't unseal their bids in time.  This is quite severe punishment, though it seems that bidder, who didn't reveal his bid in time may still get 99.5% or even 100% refund, he just needs to be patient enough.  Here is what he needs to do:

1. Wait until the name, he bid for, will be released
2. Start another auction for the same name
3. Reveal the bid during reveal phase

If he will win this time, he will release the name later and get 100% refund,  If he will loose, he will get 99.5% refund immediately.

**Comment by Arachnid** [comment]
I did consider this; however, the prospect of a name being released at some unknown time in the future seems sufficiently uncertain as to deter trying to use this deliberately, and once the auction period is over, anyone could invalidate the attacker's bid with the `cancelBid` function.

Further, the code as it is protects someone who accidentally submits transactions out of order and bids before opening an auction - as long as they open the auction, they're okay.
