### ISSUE TITLE
Failed to register subnode via FIFSRegistrar

### ISSUE THREAD

**Issue by yuanfeiz** [ethereum/ens#88]
I deployed the following version to test the contract:

```
    function getRootOwner() constant returns(address) {
        return ens.owner(rootNode);
    }
    
    function getOwner(bytes32 label) only_owner(label) constant returns(address) {
        var node = sha3(rootNode, label);
        return ens.owner(node);
    }
    
    function registerDryRun(bytes32 subnode) only_owner(subnode) {
        Register(rootNode, subnode, msg.sender);
    }

    
    function register(bytes32 subnode) only_owner(subnode) {
        ens.setSubnodeOwner(rootNode, subnode, msg.sender);
    }
```

### Error
Run out of the max limit gas on `estimateGas`.

### Test Case

- `rootNode(namehash('eth')) = 0x93cdeb708b7545dc668eb9280176169d1c33cfd8ed6f04690a0bcc88a93fc4ae` 
- `subnode(sha3('foo')) = 0x41b1a0649752af1b28b3dc29a1556eee781e4a4c3a1f7f53f90fa834de098c4d` 
- `target node(namehash('foo.eth') ) = 0xde9b09fd7c5f901e23a3f19fecc54828e9c848539801e86591bd9801b019f84f`

### Contract Result
![image](https://cloud.githubusercontent.com/assets/705367/24456340/4ef10052-14c5-11e7-82bf-3ecde5da0a4a.png)

Quote @Arachnid there're three possible issues:
> 1) You're passing the wrong ENS address to the FIFSRegistrar constructor

ENS address is correct, otherwise `getRootOwner` would fail to fetch the correct owner.

> 2) You're passing the wrong root node

Root node is fine given the following log screenshot
![image](https://cloud.githubusercontent.com/assets/705367/24458131/9dc8cff2-14ca-11e7-8cd5-16166d046d4d.png)

>3) The name is already owned by another account.

Checked the target in ENS, confirmed it was not taking.

It's quite likely not the FIFSRegistrar or ENS issues, but the answer to this issue could eventually facilitate the ENS deployment and config process.

**Comment by Arachnid** [comment]
It looks like `getRootOwner` is returning your account? The owner should be set to the registrar contract - otherwise it won't be able to make changes to ENS.

**Comment by yuanfeiz** [comment]
Yes, that's exactly the problem! It's the first time I wired up two contracts, thanks a lot for deepen my understanding!

I am aware that the manual deployment process is quite error prone, is there an automatic way to do that?

**Comment by Arachnid** [comment]
I have plans to provide scripts to do this; possibly by having a 'deployment contract' that does the deployment and connections, then selfdestructs.
