### ISSUE TITLE
Decide on additional restrictions

### ISSUE THREAD

**Issue by chris-remus** [ethereum/ens#89]
Alex wants to add additional restrictions to the registrar for launch: either a maximum auction value (above which any bids are refunded) or a longer minimum name length, in order to have a softer launch with less funds invested.

Nick is concerned that doing that is likely to cripple the name system's usefulness, or introduce extra game-theoretic issues we haven't thought through.

**Comment by chris-remus** [comment]
@Arachnid and @alexvandesande How about we start tracking this discussion here?

**Comment by alexvandesande** [comment]
Ok. So after lots of discussion it seems this is the most likely to be accepted restriction: https://github.com/ethereum/ens/pull/105 

Names will not all become available at the same time but in deterministic random moments up to 3 months.
