### ISSUE TITLE
Share current to-do list with Chris 

### ISSUE THREAD

**Issue by chris-remus** [ethereum/ens#91]
@Arachnid Please send me your current to-do list. It's the list you referenced [in our conversation earlier this week.](https://docs.google.com/document/d/1eYdW6F2yD5IrxaZWAYtLKPK0Ct5yXT1prnYZ5Q54UwI/edit)

**Comment by Arachnid** [comment]
I mentioned on the Google Doc - I meant to say that the Github issues list was my todo list, not that I had a separate todo list.

**Comment by Arachnid** [comment]
I really, really don't have one. I was saying in the call that I was using the Github issues list as my todo list.

**Comment by chris-remus** [comment]
Understood, thanks for the clarification!
