### ISSUE TITLE
Launch main ens.domains.website

### ISSUE THREAD

**Issue by chris-remus** [ethereum/ens#92]
From [Alex's list - ](https://docs.google.com/document/d/1rA37_2ucyD0VzT4JiENANr-MNSGQ67lYq1219lB_hZM/edit#)

- [ ] approve texts

**Comment by chris-remus** [comment]
➤ Chris Remus commented:
test from asana integration

**Comment by chris-remus** [comment]
@alexvandesande Can I help get these texts approved?

**Comment by Arachnid** [comment]
I believe everything relevant has already been approved. Feel free to reopen if I'm wrong.
