### ISSUE TITLE
Deploy contracts on main net

### ISSUE THREAD

**Issue by chris-remus** [ethereum/ens#95]
From [Alex's list - ](https://docs.google.com/document/d/1rA37_2ucyD0VzT4JiENANr-MNSGQ67lYq1219lB_hZM/edit#)

- [x] Test and merge final vulnerability code changes
- [ ] Write up a text explaining how the deployment process works
- [x] Deploy registrar contract
- [x] Point “.eth” to the registrar contract

**Comment by Arachnid** [comment]
>  Write up a text explaining how the deployment process works

This is largely documented on docs.ens.domains. Since it's not a launch dependency, if changes are needed, can we break this out into a separate issue?
