### ISSUE TITLE
Understand Issue and Pull priorities

### ISSUE THREAD

**Issue by chris-remus** [ethereum/ens#98]

**Comment by chris-remus** [comment]
@Arachnid and @alexvandesande Is any type of prioritization method being used, to ID the Issues and Pull requests that HAVE to be addressed before launch?

**Comment by Arachnid** [comment]
No, not at present. We should be tagging them in some fashion, you're right.

**Comment by chris-remus** [comment]
Created [new Issue](https://github.com/ethereum/ens/issues/100) to track tagging task.
